### ISSUE TITLE
What about SCK pin?

### ISSUE THREAD

**Issue by dekelm8** [MajenkoLibraries/MCPDAC#2]
Where i should connect the SCK pin on the arduino ?

**Comment by majenkotech** [comment]
To the SCK pin of course.

**Comment by dekelm8** [comment]
Sorry for dummy question (I'm new on arduino, I'm use to programming on pic)
where is that on the arduino uno ?

**Comment by majenkotech** [comment]
Where the documentation tells you it is.

**Comment by dekelm8** [comment]
is that pin 13?

**Comment by majenkotech** [comment]
Yes. Well done.

**Comment by dekelm8** [comment]
ok i so connected the SCK pin to pin 13 on arduino and SDI to pin 11 on arduino 
and it seems not working, i'm using your "triangle" example sketch

**Comment by majenkotech** [comment]
And the other required pins? And a decoupling capacitor? etc?

**Comment by dekelm8** [comment]
LDAC + Vss connected to GND, VDD to 5v, CS to pin 10, SCK to pin 13, SDI to pin 11
where i need to add decoupling cap?

**Comment by majenkotech** [comment]
Across the power of course. How are you determining that it isn't working?

**Comment by dekelm8** [comment]
i probing it to my scope, and i get 0.27v constantly, without any changes, 
also i disabled the volts += 100 and give it fixed numbers and nothing happen

**Comment by majenkotech** [comment]
And which chip are you using?

**Comment by dekelm8** [comment]
mcp4822

**Comment by majenkotech** [comment]
I can't say why it isn't working then. Use your oscilloscope to confirm the Arduino is sending the correct data. If it is, then maybe the MCP4822 is dead.

**Comment by dekelm8** [comment]
i can't see any data goes out from the arduino, i'll check it with other code and let you know 
Thanks for the help 
have great week

**Comment by dekelm8** [comment]
Simple SPI code actually work:

```
const int csPin=8;
const int latchPin=9;


void setup() {
 Serial.begin(9600);
 SPI.begin();

 pinMode(csPin, OUTPUT);
 pinMode(latchPin, OUTPUT);


 int val=0;
 for( val = 0; val < 4096; val+=500){
 int channel=0;
 int gain= 0; 
 int shutdown=1;
  
 byte lowByte = val & 0xff;
   byte highByte = ((val >> 8) & 0xff) | channel << 7 | gain << 5 | shutdown << 4;

  digitalWrite(latchPin, 1);
  digitalWrite(csPin, 0);

  SPI.transfer(highByte);
  SPI.transfer(lowByte);

  digitalWrite(csPin, 1);
  digitalWrite(latchPin, 0);

  delay (2000);
 }
}
```
